shop_customer:
    resource: "@ShopCustomerBundle/Resources/config/routing.yml"
    prefix:   /

shop_product:
    resource: "@ShopProductBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
