ProductBundle\Entity\Product:
    type: entity
    table: product
    repositoryClass: ProductBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        price:
            type: decimal
            precision: 10
            scale: 2
        quantity:
            type: integer
            length: 11
    oneToMany:
            productOrders:
                targetEntity: CustomerBundle\Entity\OrderProduct
                mappedBy: product

