customer_customer:
    resource: "@CustomerBundle/Resources/config/routing/customer.yml"
    prefix:   /customer

customer_order:
    resource: "@CustomerBundle/Resources/config/routing/order.yml"
    prefix:   /order

customer_homepage:
    path:     /customers
    defaults: { _controller: CustomerBundle:Customer:index }

order_homepage:
    path:     /
    defaults: { _controller: CustomerBundle:Order:index }
