CustomerBundle\Entity\Customer:
    type: entity
    table: customer
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        firtname:
            type: string
            length: 100
        login:
            type: string
            length: 100
            unique : true
        password:
            type: string
            length: 100
    oneToMany:
        orders:
            targetEntity: Order
            mappedBy: customer
    lifecycleCallbacks:
        prePersist: [ setPasswordValue ]
