CustomerBundle\Entity\Order:
    type: entity
    table: orders
    repositoryClass: CustomerBundle\Repository\OrderRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        sum:
            type: decimal
            precision: 10
            scale: 2
        date:
            type: datetime
    manyToOne:
        customer:
            targetEntity: Customer
            inversedBy: orders
            joinColumn:
                name: customer_id
                referencedColumnName: id
    oneToMany:
        orderProducts:
            targetEntity: OrderProduct
            mappedBy: order
            cascade : [persist] # @todo : read more details about this