CustomerBundle\Entity\Order:
    type: entity
    table: orders
    repositoryClass: CustomerBundle\Repository\OrderRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        sum:
            type: decimal
        date:
            type: datetime
    manyToOne:
        customer:
            targetEntity: Customer
            inversedBy: orders
            joinColumn:
                name: customer_id
                referencedColumnName: id
    oneToMany:
        products:
            targetEntity: ProductBundle\Entity\Product
            mappedBy: OrderProduct