CustomerBundle\Entity\OrderProduct:
    type: entity
    table: order_product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        order_id:
            type: integer
        product_id:
            type: integer
        quantity:
            type: integer
    manyToOne:
        order:
            targetEntity: Order
            inversedBy: orderProducts
            joinColumn:
                name: order_id
                referencedColumnName: id
        product:
            targetEntity: ProductBundle\Entity\Product
            inversedBy: productOrders
            joinColumn:
                name: product_id
                referencedColumnName: id

