<?php

namespace ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name,$limit = 10)
    {
        $qb = $this->createQueryBuilder('p')
            ->where('p.name like :name')
//            ->setParameter('name', '%'.$name.'%');
            ->setParameter('name', $name.'%');
        if($limit) {
            $qb->setMaxResults($limit);
        }
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
